# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: springboot
      MONGO_INITDB_ROOT_PASSWORD: spring
    ports:
      - "27017:27017"
    
